apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
data:
  jenkins-admin-user: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
type: Opaque
data:
  jenkins-admin-password: YWRtaW4=

